- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: yes
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes
- name: Add user {{ username }}
  user:
    createhome: true
    force: false
    name: "{{ username }}"
    password: "{{ user_pass }}"
    shell: /bin/bash
    update_password: always
    groups: wheel
  become: yes
- name: Set up authorized keys for the user {{ username }}
  authorized_key: user={{ username }} key="{{item}}"
  with_file:
    - /etc/ansible/roles/user-manager/files/{{ username }}.pub
  become: yes
