#!/bin/bash 

HOST=$1
IP=$2
ACTION=$3

if [ -z $HOST ]; then
	echo -e "Host vide"
	echo -e "Vous pouvez afficher la commande d'aide à l'aide du paramètre -h ou --help"
	exit 1
elif [ -z $IP ]; then
	echo -e "IP vide"
	echo -e "Vous pouvez afficher la commande d'aide à l'aide du paramètre -h ou --help"
	exit 1
elif [ -z $ACTION ]; then
	echo -e "Action vide"
	echo -e "Entrez add ou remove"
	echo -e "Vous pouvez afficher la commande d'aide à l'aide du paramètre -h ou --help"
	exit 1
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo -e "Ce script sert au déploiement de Fail2Ban sur les hôtes Linux Rocky par l'intermédiaire d'Ansible"
	echo -e "Utilisation du script : "
	echo -e "Arg 1 = hôte sur lequel déployer Fail2Ban (exemple : bali-bdd-1)"
	echo -e " "
	echo -e "Note: l'hôte doit pouvoir être accessible par l'hôte ansible via clé privée, et être renseigné dans le fichier /etc/ansible/hosts  "
	exit 0
fi

ANSIBLE_INVENTORY="/etc/ansible/hosts"

if [ "$ACTION" == "add" ]; then
	sed -i "/\[linux-rocky\]/a ${HOST} ansible_host=${IP}" ${ANSIBLE_INVENTORY}
elif [ "$ACTION" == "remove" ]; then
	sed -i "/${HOST} ansible_host=${IP}/d" ${ANSIBLE_INVENTORY}
else
	echo -e "ACTION $ACTION non reconnue"
fi

