logserver: bali-splunk-1.bali.local
ntpserver: bali-ntp-1.bali.local
monitoringserver: bali-zabbix-1.bali.local
sshport: "22"
sshloglevel: "INFO"
sshpubkeyauth: "yes"
sshpasswordauth: "no"
mysqlport: "3306"
